global:
  schedule: 12
  nofity: true

tools:
  - id: gau
    command: 'gau <target>'
    verbose: false 
    port_scan:
      run: true
      ports:
        - 21
        - 22
        - 53
        - 5432
        - 3306
        - 9092
    brute_force:
      run: true
      command: 'ffuf -u <target>/FUZZ -w <wordlist> -s -rate 10'
      regex: '^[^\/\r\n\\]+\.[^\/\r\n\\]+$'
      conditions:
        - technology: 'php'
          wordlist: '/home/caio/offsec/resources/seclists/Discovery/Web-Content/Programming-Language-Specific/Common-PHP-Filenames.txt'
        - technology: 'wordpress'
          wordlist: ''
    parser:
      type: 'realtime'
      regex: '^(https?:\/\/)?([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})(:\d+)?(\/[^\r\n]*)?$'
    
  - id: waymore
    command: 'waymore -i <target>'
    verbose: false
    port_scan:
      run: true
      ports:
        - 21
        - 22
        - 53
        - 5432
        - 3306
        - 9092
    parser:
      type: 'realtime'
      regex: '^(https?:\/\/)?([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})(:\d+)?(\/[^\r\n]*)?$'

