global:
  schedule: 12
  nofity: true
  intensity: 'aggressive'

tools:
  - id: gau
    command: 'gau <target>'
    verbose: false 
    port_scan:
      run: true
      ports:
        - 21
        - 22
        - 53
        - 5432
        - 3306
        - 9092
    brute_force:
      run: true
      command: 'ffuf -u <target>/FUZZ -w <wordlist> -s -mc 200 -rate 10'
      regex: '^\/?(?:[\w-]+(?:\.[\w-]+)*\/)*[\w-]+(?:\.[\w-]+)*\/?$'
      conditions:
        - technology: 'php'
          wordlist: '/home/caio/offsec/resources/seclists/Discovery/Web-Content/Programming-Language-Specific/Common-PHP-Filenames.txt'
        - technology: 'apache'
          wordlist: '/home/caio/offsec/resources/seclists/Discovery/Web-Content/Web-Servers/Apache.txt'
        - technology: 'nginx'
          wordlist: '/home/caio/offsec/resources/seclists/Discovery/Web-Content/Web-Servers/nginx.txt'
    parser:
      type: 'realtime'
      regex: '^(https?:\/\/)?([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})(:\d+)?(\/[^\r\n]*)?$'
    overrides:
      - scope: 'nasa.gov'
        type: 'brute_force'
        command: 'ffuf -u <target>/FUZZ -w <wordlist> -s -mc 200 -rate 30'
      - scope: 'nasa.gov'
        type: 'tool'
        command: 'gau <target> --subs'
    
  - id: waymore
    command: 'waymore -i <target>'
    verbose: false
    port_scan:
      run: true
      ports:
        - 21
        - 22
        - 53
        - 5432
        - 3306
        - 9092
    parser:
      type: 'realtime'
      regex: '^(https?:\/\/)?([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})(:\d+)?(\/[^\r\n]*)?$'

